version: '3.8'

services:
  # Serviço de Jenkins para integração contínua
  jenkins:
    build: ./jenkins                # Usa o Dockerfile localizado na pasta ./jenkins
    container_name: coco_bambu_server_jenkins  # Define um nome amigável para o contêiner
    privileged: true                # Concede permissões elevadas ao contêiner (necessário para Docker-in-Docker)
    user: root                      # Executa o contêiner como usuário root para garantir permissões
    networks:
      - bambunet            # Conecta o Jenkins à rede Docker chamada 'skynet'
    restart: always                 # Reinicia automaticamente o contêiner em caso de falha
    environment:
      - TZ=America/Sao_Paulo        # Define o fuso horário do contêiner para São Paulo
    ports:
      - "8080:8080"                 # Mapeia a porta 8080 do host para a interface web do Jenkins
      - "50000:50000"               # Mapeia a porta para comunicação com agentes Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home             # Persiste dados do Jenkins no volume 'jenkins_home'
      - /var/run/docker.sock:/var/run/docker.sock  # Permite que o Jenkins use Docker do host

# Volumes
volumes:
  jenkins_home:                 # Persistência de dados do Jenkins

# Redes
networks:
  bambunet:                       # Rede Docker para comunicação entre contêineres
    driver: bridge